//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseballEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BaseballDBEntities1 : DbContext
    {
        public BaseballDBEntities1()
            : base("name=BaseballDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    
        public virtual ObjectResult<GetTeamByPK_Result> GetTeamByPK(Nullable<int> teamnum)
        {
            var teamnumParameter = teamnum.HasValue ?
                new ObjectParameter("teamnum", teamnum) :
                new ObjectParameter("teamnum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeamByPK_Result>("GetTeamByPK", teamnumParameter);
        }
    }
}
