//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenGriffeyJrShips
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fan
    {
        public int FanPK { get; set; }
        public string FanName { get; set; }
        public Nullable<int> FavTeamFK { get; set; }
        public Nullable<int> FavPlayerFK { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
