//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenGriffeyJrEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKPosition
    {
        public int LKPositionPK { get; set; }
        public string PositionName { get; set; }
    }
}
