//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenGriffeyJrEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamPk { get; set; }
        public string TeamName { get; set; }
        public Nullable<decimal> SalaryCap { get; set; }
        public Nullable<int> LeagueFk { get; set; }
    }
}
